import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import AddBootstrap from "../components/AddBootstrap";
import Provider from "@/components/Provider";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "react-confirm-alert/src/react-confirm-alert.css";
import ContextProvide from "@/context/AppContext";
import Popup from "@/components/Popup";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ToastContainer } from "react-toastify";
import { Bounce } from "react-toastify";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KelasKu",
  description: "Generated by create next app",
  icons: {
    icon: "/KelasKu.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" data-scroll-behavior="smooth">
      <body className={openSans.className}>
        <Provider>
          <AddBootstrap />
          <ContextProvide>
            {children}
            <ToastContainer
              position="bottom-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Bounce}
            />
            <Popup />
          </ContextProvide>
        </Provider>
        <SpeedInsights />
      </body>
    </html>
  );
}
